#!/bin/zsh
# zsh aliases

# {{{ Standard
alias a='ack -i'
alias :q='exit'
alias :wq='exit'
alias df='df -kh'
alias du='du -kh'
alias egrep='egrep --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias j='jobs -l'
alias mirror="noglob wget --mirror --no-parent --recursive --timestamping --continue --recursive"
alias mkdir='nocorrect mkdir -p'
alias mmv='noglob zmv -W'
alias path='echo -e ${PATH//:/\\n}'
alias psg="ps aux | grep"
alias sudo="sudo " #This just allows aliases to be expanded after sudo
alias trail="tail -n 300 -f"
alias tree='tree -Csu'
alias e='print -l'
alias cp='nocorrect cp'
alias mv='nocorrect mv'

if which htop >/dev/null; then
    alias top='htop'
fi

# }}}

# {{{ Global
alias -g V='| vim'
alias -g L='| less -REF'
alias -g M='| more'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g C='| wc -l'
alias -g S='| sort'
alias -g A='&> /dev/null | at'
alias -g DN='&> /dev/null'
alias -g X='| xclip'
# }}}

# {{{ Suffix
alias -s bz2=show-archive
alias -s tex=${EDITOR:-vim}
alias -s dvi=xdvi
alias -s gz=show-archive
alias -s htm=${BROWSER:-lynx}
alias -s html=${BROWSER:-lynx}
alias -s tar=show-archive
alias -s tex=${EDITOR:-vim}
alias -s txt=${PAGER:-less}
alias -s zip=show-archive
# }}}

# {{{ Families

# less

alias less='less -iM'

# chmod
alias rw-='chmod 600'
alias rwx='chmod 700'
alias r--='chmod 644'
alias r-x='chmod 755'

# ls
alias ls='ls -hFG --color=auto'      # add colors for filetype recognition
alias lsa='ls -Al'                   # show hidden files
alias lsx='ls -lXB'                  # sort by extension
alias lsk='ls -lSr'                  # sort by size
alias lsk='ls -lSr'                  # sort by size
alias lsc='ls -lcr'                  # sort by change time
alias lsu='ls -lur'                  # sort by access time
alias lsr='ls -lR'                   # recursive ls
alias lst='ls -ltr'                  # sort by date
alias lsl='ls -Al L'                 # pipe through 'less'
alias lsbig='ls -flh *(.OL[1,10])'   # display the biggest files
alias lsd='ls -d *(/)'               # only show directories
alias lse='ls -d *(/^F)'             # only show empty directories
alias lsnew='ls -rl *(D.om[1,10])'   # display the newest files
alias lsold='ls -rtlh *(D.om[1,10])' # display the oldest files
alias lssmall='ls -Srl *(.oL[1,10])' # display the smallest files
# }}}

# {{{ Typos
alias xs='cd'
alias vf='cd'
alias moer='more'
alias moew='more'
alias kk='ll'
alias cd..='cd ..'
# }}}

# {{{ Git
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gd='git diff | less'
alias gl='git pull'
alias gp='git push'
alias gpcd='git push && cap deploy'
alias gs='git status'
# }}}
