#!/bin/zsh

alias a='rg -p'
alias b='bat'
alias f='fd'
alias h='http'
alias t='tree'
alias v='vim'

for c in cp rm mv chmod chown rename; do
    alias $c="nocorrect $c -v"
done

for c in alias expr find wget which; do
    alias $c="noglob $c"
done

alias di='docker images'
alias dpa='docker ps -a'
alias du='du -kh'
alias duh='du -slh'
alias mirror="noglob wget --mirror --no-parent --recursive --timestamping --continue --recursive"
alias mkdir='nocorrect mkdir -p'
alias rscp="nocorrect rsync -aP --no-whole-file --inplace"
alias scp='scp -r'
alias sudo='noglob sudo '
alias vim='nvim'

# zmv

alias mmv='noglob zmv -W'
alias zmv='noglob zmv'
alias zcp='noglob zmv -C'
alias zln='noglob zmv -L'

# global

alias -g C='| wc -l'
alias -g G='| grep -i'
alias -g H='| head'
alias -g J="| jq '.'"
alias -g L='| less -REF'
alias -g N='&> /dev/null'
alias -g S='| sort'
alias -g T='| tail'
alias -g V='| vim'
