#!/bin/zsh

alias @='grt'
alias b='bat'
alias e=$EDITOR
alias f='fd'
alias g='_g'
alias h='http'
alias l='exa --all --git --long --icons'
alias r='rg -p'
alias t='tree'
alias v=$VISUAL

for c in cp rm mv chmod chown rename; do
    alias $c="nocorrect $c -v"
done

for c in alias expr find wget which; do
    alias $c="noglob $c"
done

alias di='docker images'
alias dpa='docker ps -a'

alias fzf=fzf-tmux
alias mkdir='nocorrect mkdir -p'
alias mmv='noglob zmv -W'
alias rscp="nocorrect rsync -aP --no-whole-file --inplace"
alias scp='scp -r'
alias sudo='noglob sudo '

alias -g C='| wc -l'
alias -g G='| grep -i'
alias -g H='| head'
alias -g J="| jq '.'"
alias -g L='| less -REF'
alias -g N='&> /dev/null'
alias -g S='| sort'
alias -g T='| tail'
alias -g V='| vim'
