#!/bin/zsh

alias @='grt'
alias b='bat'
alias d='docker'
alias e="tmux split-window -h $EDITOR"
alias f='fd'
alias h='http'
alias k='kubectl'
alias l='exa --all --git --long --icons'
alias t='tree'
alias u='$EDITOR "$(git rev-parse --show-toplevel 2>/dev/null || echo .)/.git/index"'
alias v=$VISUAL
alias y='yarn'

for c in cp rm mv chmod chown rename; do
    alias $c="nocorrect $c -v"
done

for c in alias expr find wget which; do
    alias $c="noglob $c"
done

alias hd='h -d'
alias vd='v -d'
alias ri='r -i'

alias di='docker images'
alias dnl='docker network ls'
alias dsl='docker stack ls'
alias dpa='docker ps -a'
alias dpaf='docker ps -a --format "table {{.Names}}\t{{.ID}}\t{{.Image}}\t{{.Status}}" | (sed -u 1q; sort)'

alias calc='noglob zcalc'
alias fzf=fzf-tmux
alias ipinfo='curl -s ipinfo.io | jq .'
alias mkdir='nocorrect mkdir -p'
alias mmv='noglob zmv -W'
alias panic="curl -s https://corona-stats.online\?format=json | jq '.data[] | select(.countryCode==\"GB\") | { cases, todayCases, deaths, todayDeaths, oneDeathPerPeople }'"
alias pubkey="pbcopy < ~/.ssh/id_rsa.pub && echo '=> Public key yanked.'"
alias rscp="nocorrect rsync -aP --no-whole-file --inplace"
alias scp='scp -r'
alias sudo='noglob sudo '
alias ungzip='gzip -d'
alias untar='tar xvf'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
alias weather='curl -s v2.wttr.in/Glasgow,UK'

alias -s git='git clone'

alias -g B='| bat'
alias -g C='| wc -l'
alias -g CA='2>&1 | cat -A'
alias -g G='| rg -i'
alias -g H='| head'
alias -g J="| jq '.'"
alias -g L='| less -REF'
alias -g LS='| less -RS'
alias -g N='&> /dev/null'
alias -g NF='./*(oc[1])'
alias -g NN='> /dev/null 2>&1'
alias -g P='| column -t'
alias -g S='| sort'
alias -g T='| tail'
alias -g U='| uniq'
alias -g V='| v'
alias -g X='| clipcopy'
alias -g Z='| fzf-tmux'

alias -g CF1="| tr -s ' ' | cut -d' ' -f1"
alias -g CF2="| tr -s ' ' | cut -d' ' -f2"
alias -g CF3="| tr -s ' ' | cut -d' ' -f3"
